### ISSUE TITLE
Coexistence with actual ROAM receiver?

### ISSUE THREAD

**Issue by WestfW** [ecodina/hunter-wifi#1]
Do you happen to know if the electrical setup allows the ESP to be connected in parallel with the actual Hunter receiver (both connected at the same time?)

**Comment by ecodina** [comment]
I don't have the actual Hunter receiver so I can't test it. However I don't think it would work as you would connect the REM pin with two "RX" GPIO pins. Without any protection, if you sent a command from one device, the other one may break or behave unexpectedly.
