### ISSUE TITLE
No response from hunter x-core after sending command

### ISSUE THREAD

**Issue by viperk1** [ecodina/hunter-wifi#14]
Hi there, I've just set up this project on a d1mini. Flashed and connected to the floating power source and the hunter as documented. When I send a command, I get a success back on the result topic, but nothing actually happens at the hunter. The only change I made to the project is to use D1 instead of D0.

How do I go about debugging this?

Help is much appreciated!

**Comment by viperk1** [comment]
So although my splicing of the power supply tested to be electrically sound, the whole circuit just didn't seem to like it. I found another project which plugged the 24 VAC directly into the 3.3V header on the d1mini. I tried that, and it did the trick! Closing with this comment in case anyone else runs into this.

**Comment by loopy321** [comment]
> So although my splicing of the power supply tested to be electrically sound, the whole circuit just didn't seem to like it. I found another project which plugged the 24 VAC directly into the 3.3V header on the d1mini. I tried that, and it did the trick! Closing with this comment in case anyone else runs into this.

Can you please share the 24vac to 3.3v project?

**Comment by viperk1** [comment]
> Can you please share the 24vac to 3.3v project?

Here it is: https://www.loullingen.lu/projekte/Hunter/index.php?language=EN

I also appreciated his screenshots which let me know that all this works while the hunter dial is set to 'off'.

**Comment by khayamgondal** [comment]
@loopy321 did you connect 24V to 3.3v pin on the board? Asking before I fry my board :p
