### ISSUE TITLE
New doc pages

### ISSUE THREAD

**Issue by loopy321** [ecodina/hunter-wifi#16]
The new doc pages look great, but some of the links got broken, such as to the images of the wiring.  

i.e. the following do not load for me:
https://ecodina.github.io/hunter-wifi/#!docs/1%20Build%20and%20upload.md
https://ecodina.github.io/hunter-wifi/#!docs/2%20Connection%20to%20the%20SmartPort.md

**Comment by loopy321** [comment]
The pages you posted work, but I followed the link to the documentation from the main page of ("A quite extensive documentation is available on [this webpage](https://ecodina.github.io/hunter-wifi)."):   https://github.com/ecodina/hunter-wifi

Which points to https://ecodina.github.io/hunter-wifi/#!index.md

which has hrefs to: https://ecodina.github.io/hunter-wifi/#!docs/1%20Build%20and%20upload.md

I tried this on another linux box with firefox and had the same result.

Maybe github problem... This morning I saw this:
![image](https://user-images.githubusercontent.com/1026345/175021738-b4b83d56-9bb8-43e8-b339-030fddac8a1d.png)

**Comment by ecodina** [comment]
Fixed! It was due to a recent change in the documentation structure.
