### ISSUE TITLE
Any ability to stop a program?

### ISSUE THREAD

**Issue by viperk1** [ecodina/hunter-wifi#17]
It's not in the docs, but I don't know if that means it hasn't been included yet, or if the capability isn't there.

I've tried using http://host/api/stop/program/1 but I just get a page back with the text "This is the API root"

Should be a quick yes/no answer 😄 

Thank you!

**Comment by ecodina** [comment]
No,  you can only stop individual zones.

As an alternative: if you know which zones are included in the program you
want to stop, you could stop each of them from wherever you control the
system
