### ISSUE TITLE
ESP Continuous reboot 

### ISSUE THREAD

**Issue by ccmmgg** [ecodina/hunter-wifi#19]
Installed precompiled firmware from latest release. I am using a D1 Mini Pro (ESP-8266EX)

Monitoring shows this as device reboots every 10 seconds or so:

```
␐�!␛␐���1�)�␙␔␎␘�mounting FS...
mounted file system
reading config file
opened config file
{"mqtt_server":"","mqtt_port":0,"mqtt_username":"","mqtt_password":""}
json successfully parsed
*WM: Adding parameter
*WM: server
*WM: Adding parameter
*WM: port
*WM: Adding parameter
*WM: username
*WM: Adding parameter
*WM: password
*WM:
*WM: AutoConnect Try No.:
*WM: 0
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.1.214
mDNS responder started

IP address: 192.168.1.214
:0
Ready! Open http://X-CORE.local in your browser

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffd40 end: 3fffffc0 offset: 01a0
3ffffee0:  feef0030 00000000 40228ac4 ffffffff  
3ffffef0:  3fff117c 3fff11f8 3fff1198 4022749d  
3fffff00:  3fff3634 3fff118c 3fff1198 40212d03  
3fffff10:  feefeffe feefeffe feefeffe feefeffe  
3fffff20:  00000000 3ffe8da5 00000000 00000000  
3fffff30:  00000001 00000000 3fff3b24 3fff3b14  
3fffff40:  40209f74 00000000 00000000 3fff15fc  
3fffff50:  3fffdad0 3fff11f8 3fff1288 40212f4c  
3fffff60:  00000000 3ffe8e60 00000001 3fff3f4c  
3fffff70:  feefef20 feefeffe feefeffe 402075f1  
3fffff80:  00000000 3ffe8e60 3fff117c 4022749d  
3fffff90:  feefeffe 3fff11f8 3fff117c 40205947  
3fffffa0:  3fffdad0 00000000 3fff15e8 402230ec  
3fffffb0:  feefeffe feefeffe 3ffe88e0 401003f5  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------
```

**Comment by ccmmgg** [comment]
I believe the issue is with MQTT. I hadn't set any mqtt client settings and setting enableMQTT = false fixed the problem. I will work on a PR to toggle whether to use MQTT if i can figure it out.

**Comment by ccmmgg** [comment]
See PR #20 for toggling MQTT during captive portal setup. Also includes some groundwork for a web UI at http://<espIP>/control

**Comment by ecodina** [comment]
PR merged. Closing this issue

**Comment by natanielj** [comment]
Hi I'm still getting this issue with a esp8266 module, the enable_mqtt:false shows up in the error and the toggle does not show up in the wifi config either. 

`3ffffed0:  00000000 3fff118c 3fff1244 4020b414  
3ffffee0:  736c6166 00000000 40228ac4 ffffffff  
3ffffef0:  3fff117c 3fff11f8 3fff1198 4022749d  
3fffff00:  3fff3634 3fff118c 3fff1198 40212d60  
3fffff10:  feefeffe feefeffe feefeffe feefeffe  
3fffff20:  00000000 3ffe8da5 00000000 00000000  
3fffff30:  00000001 00000000 3fff3b24 3fff3b14  
3fffff40:  40209f74 00000000 00000000 3fff15fc  
3fffff50:  3fffdad0 3fff11f8 3fff1288 40212f4c  
3fffff60:  00000000 3ffe8e60 00000001 3fff3f3c  
3fffff70:  feefef20 feefeffe feefeffe 402075f1  
3fffff80:  00000000 3ffe8e60 3fff117c 4022749d  
3fffff90:  feefeffe 3fff11f8 3fff117c 40205947  
3fffffa0:  3fffdad0 00000000 3fff15e8 402230ec  
3fffffb0:  feefeffe feefeffe 3ffe88e0 401003f5  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------
�%�����B���B�mounting FS...
mounted file system
reading config file
opened config file
{"mqtt_server":"","mqtt_port":0,"mqtt_username":"","mqtt_password":"","mqtt_enable":false}
json successfully parsed
*WM: Adding parameter
*WM: server
*WM: Adding parameter`

I tried compiling it myself with platformIO but nothing shows up on the serial monitor unless i'm building it incorrectly. Any help would be great.
