### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by moscheIT** [ecodina/hunter-wifi#23]
Hello 

 when i try to compile the sources i get this error
```

Compiling .pio/build/d1_mini/src/wifi.cpp.o
src/web_server.cpp: In function 'void setup_APIRoutes()':
src/web_server.cpp:63:21: error: 'handleNotFound' was not declared in this scope
   63 |   server.onNotFound(handleNotFound);
      |                     ^~~~~~~~~~~~~~
In file included from src/wifi.cpp:10:
include/mqtt.h:21:8: error: 'WiFiClient' does not name a type
   21 | extern WiFiClient espClient;
      |        ^~~~~~~~~~
*** [.pio/build/d1_mini/src/web_server.cpp.o] Error 1
*** [.pio/build/d1_mini/src/wifi.cpp.o] Error 1

```

what other details can I provide to help

**Comment by ccmmgg** [comment]
hi @moscheIT, I fixed the issue described here in PR #24

if you can, please test on your machine and I will merge into master.

**Comment by ccmmgg** [comment]
I merged #25. @moscheIT let me know if you still have problems compiling.

**Comment by moscheIT** [comment]
I'm late due to work. i tried and it works thanks @ccmmgg




Il ven 9 set 2022, 23:29 ccmmgg ***@***.***> ha scritto:

**Comment by ccmmgg** [comment]
@moscheIT Thanks for testing. My apologies for taking so long to get to this, work and kids delayed me as well.
