### ISSUE TITLE
Content-Type not sent in the webhook

### ISSUE THREAD

**Issue by anubisg1** [ecodina/hunter-wifi#5]
while troubleshooting my server on why it could not decode the json response i found out that the wemos doesn't include the content-type in the HTTP response.

with manual curl

```
curl -X POST -H "Content-Type: application/json" -d '{"action": "Start zone 2 for 1 minutes.","action_num": 1,"zone": 2,"result": "No error.","result_num": 0}' http://192.168.0.2:8123/api/webhook/zone_start
```

my application works perfectly, but when i get the response from my wemos it doesn't work. 
when doing a capture (see below screenshot), the content-type is missing

![image](https://user-images.githubusercontent.com/4518931/134061569-f0d90286-3621-4a51-af04-3ad2231521ba.png)

**Comment by ecodina** [comment]
Fix merged.

**Comment by anubisg1** [comment]
Thank you for accepting my PR
